-- Tabulka karet + seed (spusť v Supabase SQL Editoru).
-- Po vytvoření tabulky nastav RLS podle potřeby, např.:
--   ALTER TABLE public.pokemon_cards ENABLE ROW LEVEL SECURITY;
--   CREATE POLICY "Veřejné čtení" ON public.pokemon_cards FOR SELECT USING (true);
--   CREATE POLICY "Veřejné vkládání" ON public.pokemon_cards FOR INSERT WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.pokemon_cards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  card_set text NOT NULL,
  year integer NOT NULL,
  condition text NOT NULL,
  price_czk numeric(12, 2),
  image_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.pokemon_cards (name, card_set, year, condition, price_czk, image_url)
VALUES
  ('Charizard', 'Base Set', 1999, 'Mint', NULL, NULL),
  ('Pikachu', 'Jungle', 1999, 'Good', NULL, NULL),
  ('Blastoise', 'Base Set', 1999, 'Near Mint', NULL, NULL);

-- Spusť jednou po vytvoření tabulky. Při opakování smaž duplicity ručně nebo použij UNIQUE.
