import type { CategoryId, CategoryMeta, Word } from "./types";

export const VOCABULARY_CATEGORIES: readonly CategoryMeta[] = [
  {
    id: "colors",
    titleCs: "Barvy",
    titleEn: "Colors",
    subtitleCs: "Odstíny a barvy",
    tileEmoji: "🎨",
    tileClass:
      "from-amber-200 via-yellow-100 to-orange-100 border-amber-300/80 text-amber-900",
  },
  {
    id: "furniture",
    titleCs: "Nábytek a místnosti",
    titleEn: "Furniture & rooms",
    subtitleCs: "Doma v místnostech",
    tileEmoji: "🛋️",
    tileClass:
      "from-cyan-200 via-teal-100 to-sky-100 border-teal-300/80 text-teal-900",
  },
  {
    id: "toys",
    titleCs: "Hračky",
    titleEn: "Toys",
    subtitleCs: "Hry a hračky",
    tileEmoji: "🧸",
    tileClass:
      "from-rose-200 via-pink-100 to-fuchsia-100 border-rose-300/80 text-rose-900",
  },
  {
    id: "body",
    titleCs: "Části těla",
    titleEn: "Body parts",
    subtitleCs: "Od hlavy k patě",
    tileEmoji: "🦶",
    tileClass:
      "from-lime-200 via-emerald-100 to-teal-100 border-emerald-300/80 text-emerald-900",
  },
  {
    id: "food",
    titleCs: "Jídlo",
    titleEn: "Food",
    subtitleCs: "Jídlo a nápoje",
    tileEmoji: "🍎",
    tileClass:
      "from-orange-200 via-amber-100 to-yellow-100 border-orange-300/80 text-orange-950",
  },
  {
    id: "numbers",
    titleCs: "Čísla",
    titleEn: "Numbers",
    subtitleCs: "Počítání",
    tileEmoji: "🔢",
    tileClass:
      "from-indigo-200 via-violet-100 to-purple-100 border-indigo-300/80 text-indigo-950",
  },
  {
    id: "school",
    titleCs: "Škola",
    titleEn: "School",
    subtitleCs: "Ve třídě",
    tileEmoji: "🎒",
    tileClass:
      "from-sky-200 via-blue-100 to-indigo-100 border-sky-300/80 text-sky-950",
  },
  {
    id: "toBe",
    titleCs: "Sloveso To Be",
    titleEn: "Verb To Be",
    subtitleCs: "Být nebo nebýt",
    tileEmoji: "🔵",
    tileClass:
      "from-blue-200 via-sky-100 to-cyan-100 border-blue-300/80 text-blue-950",
  },
  {
    id: "toHave",
    titleCs: "Sloveso To Have",
    titleEn: "Verb To Have",
    subtitleCs: "Mít a vlastnit",
    tileEmoji: "🟢",
    tileClass:
      "from-emerald-200 via-green-100 to-lime-100 border-emerald-300/80 text-emerald-950",
  },
] as const;

export const VOCABULARY_WORDS: readonly Word[] = [
  // Barvy
  { id: "black", en: "black", cs: "černá", emoji: "⚫", sentence: "The cat is black.", categoryId: "colors" },
  { id: "blue", en: "blue", cs: "modrá", emoji: "🔵", sentence: "The sky is blue today.", categoryId: "colors" },
  { id: "brown", en: "brown", cs: "hnědá", emoji: "🟤", sentence: "My shoes are brown.", categoryId: "colors" },
  {
    id: "green",
    en: "green",
    cs: "zelená",
    emoji: "🟢",
    sentence: "The grass is green.",
    categoryId: "colors",
  },
  {
    id: "orange",
    en: "orange",
    cs: "oranžová",
    emoji: "🟠",
    sentence: "I like orange juice.",
    categoryId: "colors",
  },
  { id: "pink", en: "pink", cs: "růžová", emoji: "🩷", sentence: "She has a pink bag.", categoryId: "colors" },
  {
    id: "purple",
    en: "purple",
    cs: "fialová",
    emoji: "🟣",
    sentence: "The flower is purple.",
    categoryId: "colors",
  },
  { id: "red", en: "red", cs: "červená", emoji: "🔴", sentence: "The apple is red.", categoryId: "colors" },
  { id: "white", en: "white", cs: "bílá", emoji: "⚪", sentence: "The snow is white.", categoryId: "colors" },
  {
    id: "yellow",
    en: "yellow",
    cs: "žlutá",
    emoji: "🟡",
    sentence: "The sun is yellow.",
    categoryId: "colors",
  },

  // Nábytek a místnosti
  {
    id: "bathroom",
    en: "bathroom",
    cs: "koupelna",
    emoji: "🛁",
    sentence: "I brush my teeth in the bathroom.",
    categoryId: "furniture",
  },
  { id: "bed", en: "bed", cs: "postel", emoji: "🛏️", sentence: "I sleep in my bed at night.", categoryId: "furniture" },
  {
    id: "bookcase",
    en: "bookcase",
    cs: "knihovna",
    emoji: "📚",
    sentence: "The books are in the bookcase.",
    categoryId: "furniture",
  },
  {
    id: "bunk-bed",
    en: "bunk bed",
    cs: "patrová postel",
    emoji: "🛏️",
    sentence: "My friend sleeps on the bunk bed.",
    categoryId: "furniture",
  },
  { id: "chair", en: "chair", cs: "židle", emoji: "🪑", sentence: "I sit on a chair.", categoryId: "furniture" },
  {
    id: "cupboard",
    en: "cupboard",
    cs: "skříňka",
    emoji: "🗄️",
    sentence: "The cups are in the cupboard.",
    categoryId: "furniture",
  },
  {
    id: "fireplace",
    en: "fireplace",
    cs: "krb",
    emoji: "🔥",
    sentence: "It is warm near the fireplace.",
    categoryId: "furniture",
  },
  {
    id: "kitchen",
    en: "kitchen",
    cs: "kuchyně",
    emoji: "🍳",
    sentence: "We cook in the kitchen.",
    categoryId: "furniture",
  },
  {
    id: "painting",
    en: "painting",
    cs: "obraz",
    emoji: "🖼️",
    sentence: "There is a painting on the wall.",
    categoryId: "furniture",
  },
  { id: "rug", en: "rug", cs: "koberec", emoji: "🟫", sentence: "The rug is on the floor.", categoryId: "furniture" },
  {
    id: "sitting-room",
    en: "sitting room",
    cs: "obývací pokoj",
    emoji: "🛋️",
    sentence: "We sit in the sitting room.",
    categoryId: "furniture",
  },
  { id: "sofa", en: "sofa", cs: "pohovka", emoji: "🛋️", sentence: "We relax on the sofa.", categoryId: "furniture" },
  { id: "table", en: "table", cs: "stůl", emoji: "🍽️", sentence: "We eat at the table.", categoryId: "furniture" },
  {
    id: "toy-box",
    en: "toy box",
    cs: "krabice na hračky",
    emoji: "📦",
    sentence: "My toys are in the toy box.",
    categoryId: "furniture",
  },
  { id: "vase", en: "vase", cs: "váza", emoji: "🏺", sentence: "The flowers are in the vase.", categoryId: "furniture" },
  {
    id: "wardrobe",
    en: "wardrobe",
    cs: "skříň",
    emoji: "🚪",
    sentence: "My clothes are in the wardrobe.",
    categoryId: "furniture",
  },
  {
    id: "washing-machine",
    en: "washing machine",
    cs: "pračka",
    emoji: "🧺",
    sentence: "Mum uses the washing machine.",
    categoryId: "furniture",
  },
  { id: "on", en: "on", cs: "na", emoji: "⬆️", sentence: "The book is on the table.", categoryId: "furniture" },
  { id: "in", en: "in", cs: "v", emoji: "📦", sentence: "The cat is in the box.", categoryId: "furniture" },
  { id: "under", en: "under", cs: "pod", emoji: "⬇️", sentence: "The ball is under the chair.", categoryId: "furniture" },

  // Hračky
  { id: "ball", en: "ball", cs: "míč", emoji: "⚽", sentence: "I kick a ball in the park.", categoryId: "toys" },
  { id: "bike", en: "bike", cs: "kolo", emoji: "🚲", sentence: "I ride my bike to school.", categoryId: "toys" },
  {
    id: "board-game",
    en: "board game",
    cs: "stolní hra",
    emoji: "🎲",
    sentence: "We play a board game at home.",
    categoryId: "toys",
  },
  { id: "car", en: "car", cs: "auto", emoji: "🚗", sentence: "My toy car is red.", categoryId: "toys" },
  { id: "cards", en: "cards", cs: "karty", emoji: "🃏", sentence: "We play with cards.", categoryId: "toys" },
  {
    id: "computer-game",
    en: "computer game",
    cs: "počítačová hra",
    emoji: "🎮",
    sentence: "I play a computer game on Friday.",
    categoryId: "toys",
  },
  {
    id: "dinosaur",
    en: "dinosaur",
    cs: "dinosaurus",
    emoji: "🦕",
    sentence: "The dinosaur toy is big.",
    categoryId: "toys",
  },
  { id: "doll", en: "doll", cs: "panenka", emoji: "🪆", sentence: "My doll has a blue dress.", categoryId: "toys" },
  {
    id: "draughts",
    en: "draughts",
    cs: "dáma",
    emoji: "♟️",
    sentence: "We play draughts after school.",
    categoryId: "toys",
  },
  {
    id: "football",
    en: "football",
    cs: "fotbal",
    emoji: "⚽",
    sentence: "I like playing football.",
    categoryId: "toys",
  },
  { id: "lorry", en: "lorry", cs: "nákladní auto", emoji: "🚛", sentence: "The lorry carries boxes.", categoryId: "toys" },
  {
    id: "ludo",
    en: "ludo",
    cs: "Člověče nezlob se",
    emoji: "🎲",
    sentence: "We play Ludo with my sister.",
    categoryId: "toys",
  },
  {
    id: "racing-car",
    en: "racing car",
    cs: "závodní auto",
    emoji: "🏎️",
    sentence: "The racing car is very fast.",
    categoryId: "toys",
  },
  { id: "robot", en: "robot", cs: "robot", emoji: "🤖", sentence: "My robot can walk.", categoryId: "toys" },
  { id: "rocket", en: "rocket", cs: "raketa", emoji: "🚀", sentence: "The rocket flies to space.", categoryId: "toys" },
  {
    id: "rollerblades",
    en: "rollerblades",
    cs: "in-line brusle",
    emoji: "🛼",
    sentence: "I wear rollerblades in the park.",
    categoryId: "toys",
  },
  {
    id: "skateboard",
    en: "skateboard",
    cs: "skateboard",
    emoji: "🛹",
    sentence: "He rides a skateboard.",
    categoryId: "toys",
  },
  {
    id: "skittles",
    en: "skittles",
    cs: "kuželky",
    emoji: "🎳",
    sentence: "We play skittles in the garden.",
    categoryId: "toys",
  },
  {
    id: "snakes-and-ladders",
    en: "snakes and ladders",
    cs: "hadi a žebříky",
    emoji: "🐍",
    sentence: "We play Snakes and Ladders.",
    categoryId: "toys",
  },
  { id: "train", en: "train", cs: "vlak", emoji: "🚂", sentence: "The train goes choo-choo.", categoryId: "toys" },

  // Části těla
  { id: "arm", en: "arm", cs: "paže", emoji: "💪", sentence: "I wave with my arm.", categoryId: "body" },
  { id: "body", en: "body", cs: "tělo", emoji: "🧍", sentence: "I wash my body in the bath.", categoryId: "body" },
  { id: "foot", en: "foot", cs: "chodidlo", emoji: "🦶", sentence: "I hurt my foot yesterday.", categoryId: "body" },
  { id: "leg", en: "leg", cs: "noha", emoji: "🦵", sentence: "I run fast on my legs.", categoryId: "body" },
  { id: "head", en: "head", cs: "hlava", emoji: "🙂", sentence: "I nod my head.", categoryId: "body" },
  { id: "eye", en: "eye", cs: "oko", emoji: "👁️", sentence: "I close one eye.", categoryId: "body" },
  { id: "ear", en: "ear", cs: "ucho", emoji: "👂", sentence: "I hear with my ear.", categoryId: "body" },
  { id: "nose", en: "nose", cs: "nos", emoji: "👃", sentence: "I touch my nose.", categoryId: "body" },
  { id: "mouth", en: "mouth", cs: "ústa", emoji: "👄", sentence: "I open my mouth to speak.", categoryId: "body" },
  { id: "hand", en: "hand", cs: "ruka", emoji: "✋", sentence: "I write with my hand.", categoryId: "body" },

  // Jídlo
  { id: "apple", en: "apple", cs: "jablko", emoji: "🍎", sentence: "I eat an apple every day.", categoryId: "food" },
  {
    id: "apricot",
    en: "apricot",
    cs: "meruňka",
    emoji: "🍑",
    sentence: "The apricot is sweet.",
    categoryId: "food",
  },
  { id: "banana", en: "banana", cs: "banán", emoji: "🍌", sentence: "Monkeys like bananas.", categoryId: "food" },
  {
    id: "biscuits",
    en: "biscuits",
    cs: "sušenky",
    emoji: "🍪",
    sentence: "We have biscuits for tea.",
    categoryId: "food",
  },
  {
    id: "breakfast",
    en: "breakfast",
    cs: "snídaně",
    emoji: "🍳",
    sentence: "I eat breakfast at seven.",
    categoryId: "food",
  },
  {
    id: "chocolate",
    en: "chocolate",
    cs: "čokoláda",
    emoji: "🍫",
    sentence: "I love chocolate cake.",
    categoryId: "food",
  },
  { id: "dinner", en: "dinner", cs: "večeře", emoji: "🍽️", sentence: "We have dinner at six.", categoryId: "food" },
  {
    id: "ice-cream",
    en: "ice cream",
    cs: "zmrzlina",
    emoji: "🍦",
    sentence: "Ice cream is cold and sweet.",
    categoryId: "food",
  },
  { id: "lemon", en: "lemon", cs: "citrón", emoji: "🍋", sentence: "The lemon is sour.", categoryId: "food" },
  { id: "lunch", en: "lunch", cs: "oběd", emoji: "🥪", sentence: "I pack lunch for school.", categoryId: "food" },
  { id: "milk", en: "milk", cs: "mléko", emoji: "🥛", sentence: "I drink milk in the morning.", categoryId: "food" },
  {
    id: "milkshake",
    en: "milkshake",
    cs: "mléčný koktejl",
    emoji: "🥤",
    sentence: "I make a milkshake with milk.",
    categoryId: "food",
  },
  {
    id: "mushrooms",
    en: "mushrooms",
    cs: "houby",
    emoji: "🍄",
    sentence: "We cook mushrooms for soup.",
    categoryId: "food",
  },
  { id: "olives", en: "olives", cs: "olivy", emoji: "🫒", sentence: "Olives are in the salad.", categoryId: "food" },
  { id: "pasta", en: "pasta", cs: "těstoviny", emoji: "🍝", sentence: "We eat pasta on Tuesday.", categoryId: "food" },
  { id: "peach", en: "peach", cs: "broskev", emoji: "🍑", sentence: "The peach is soft and sweet.", categoryId: "food" },
  { id: "pear", en: "pear", cs: "hruška", emoji: "🍐", sentence: "I bite a green pear.", categoryId: "food" },
  {
    id: "peppers",
    en: "peppers",
    cs: "papriky",
    emoji: "🫑",
    sentence: "Red peppers are in the salad.",
    categoryId: "food",
  },
  { id: "pizza", en: "pizza", cs: "pizza", emoji: "🍕", sentence: "We share a pizza on Friday.", categoryId: "food" },
  { id: "plum", en: "plum", cs: "švestka", emoji: "🟣", sentence: "The plum is purple.", categoryId: "food" },
  {
    id: "sandwich",
    en: "sandwich",
    cs: "sendvič",
    emoji: "🥪",
    sentence: "I make a cheese sandwich.",
    categoryId: "food",
  },
  { id: "snack", en: "snack", cs: "svačina", emoji: "🍿", sentence: "I have a snack after school.", categoryId: "food" },
  { id: "steak", en: "steak", cs: "steak", emoji: "🥩", sentence: "Dad cooks steak on Sunday.", categoryId: "food" },
  { id: "sweets", en: "sweets", cs: "cukroví", emoji: "🍬", sentence: "I eat sweets on holidays.", categoryId: "food" },
  { id: "tea", en: "tea", cs: "čaj", emoji: "🫖", sentence: "Grandma drinks tea with honey.", categoryId: "food" },

  // Čísla
  { id: "one", en: "one", cs: "jedna", emoji: "1️⃣", sentence: "I have one little brother.", categoryId: "numbers" },
  { id: "two", en: "two", cs: "dva", emoji: "2️⃣", sentence: "I see two birds.", categoryId: "numbers" },
  { id: "three", en: "three", cs: "tři", emoji: "3️⃣", sentence: "Three cats sit on the wall.", categoryId: "numbers" },
  { id: "four", en: "four", cs: "čtyři", emoji: "4️⃣", sentence: "I am four years old.", categoryId: "numbers" },
  { id: "five", en: "five", cs: "pět", emoji: "5️⃣", sentence: "School starts at five past eight.", categoryId: "numbers" },
  { id: "six", en: "six", cs: "šest", emoji: "6️⃣", sentence: "Six ducks swim in the pond.", categoryId: "numbers" },
  { id: "seven", en: "seven", cs: "sedm", emoji: "7️⃣", sentence: "I wake up at seven o'clock.", categoryId: "numbers" },
  { id: "eight", en: "eight", cs: "osm", emoji: "8️⃣", sentence: "Eight friends play together.", categoryId: "numbers" },
  { id: "nine", en: "nine", cs: "devět", emoji: "9️⃣", sentence: "Nine apples are in the bowl.", categoryId: "numbers" },
  { id: "ten", en: "ten", cs: "deset", emoji: "🔟", sentence: "I can count to ten.", categoryId: "numbers" },
  {
    id: "eleven",
    en: "eleven",
    cs: "jedenáct",
    emoji: "1️⃣1️⃣",
    sentence: "My cousin is eleven.",
    categoryId: "numbers",
  },
  {
    id: "twelve",
    en: "twelve",
    cs: "dvanáct",
    emoji: "1️⃣2️⃣",
    sentence: "There are twelve months in a year.",
    categoryId: "numbers",
  },
  {
    id: "thirteen",
    en: "thirteen",
    cs: "třináct",
    emoji: "1️⃣3️⃣",
    sentence: "Room thirteen is our classroom.",
    categoryId: "numbers",
  },
  {
    id: "fourteen",
    en: "fourteen",
    cs: "čtrnáct",
    emoji: "1️⃣4️⃣",
    sentence: "Fourteen days make two weeks.",
    categoryId: "numbers",
  },
  {
    id: "fifteen",
    en: "fifteen",
    cs: "patnáct",
    emoji: "1️⃣5️⃣",
    sentence: "The bus leaves at fifteen past three.",
    categoryId: "numbers",
  },
  {
    id: "sixteen",
    en: "sixteen",
    cs: "šestnáct",
    emoji: "1️⃣6️⃣",
    sentence: "She is sixteen years old.",
    categoryId: "numbers",
  },
  {
    id: "seventeen",
    en: "seventeen",
    cs: "sedmnáct",
    emoji: "1️⃣7️⃣",
    sentence: "Seventeen students are in my class.",
    categoryId: "numbers",
  },
  {
    id: "eighteen",
    en: "eighteen",
    cs: "osmnáct",
    emoji: "1️⃣8️⃣",
    sentence: "You can vote at eighteen.",
    categoryId: "numbers",
  },
  {
    id: "nineteen",
    en: "nineteen",
    cs: "devatenáct",
    emoji: "1️⃣9️⃣",
    sentence: "Nineteen is my lucky number.",
    categoryId: "numbers",
  },
  {
    id: "twenty",
    en: "twenty",
    cs: "dvacet",
    emoji: "2️⃣0️⃣",
    sentence: "I count up to twenty.",
    categoryId: "numbers",
  },

  // Škola
  { id: "book", en: "book", cs: "kniha", emoji: "📖", sentence: "I read a book every evening.", categoryId: "school" },
  {
    id: "rubber",
    en: "rubber",
    cs: "guma",
    emoji: "✏️",
    sentence: "I use a rubber when I make a mistake.",
    categoryId: "school",
  },
  { id: "ruler", en: "ruler", cs: "pravítko", emoji: "📏", sentence: "I draw a line with a ruler.", categoryId: "school" },
  {
    id: "pencil",
    en: "pencil",
    cs: "tužka",
    emoji: "✏️",
    sentence: "I write with a pencil.",
    categoryId: "school",
  },
  { id: "pen", en: "pen", cs: "pero", emoji: "🖊️", sentence: "My pen is blue.", categoryId: "school" },
  {
    id: "pencil-case",
    en: "pencil case",
    cs: "pouzdro",
    emoji: "🧰",
    sentence: "My pencils are in the pencil case.",
    categoryId: "school",
  },
  { id: "glue", en: "glue", cs: "lepidlo", emoji: "🧴", sentence: "I use glue for my picture.", categoryId: "school" },
  {
    id: "school",
    en: "school",
    cs: "škola",
    emoji: "🏫",
    sentence: "I walk to school with Mum.",
    categoryId: "school",
  },
  {
    id: "classroom",
    en: "classroom",
    cs: "třída",
    emoji: "🚪",
    sentence: "Our classroom is bright and big.",
    categoryId: "school",
  },
  {
    id: "pupils",
    en: "pupils",
    cs: "žáci",
    emoji: "👧",
    sentence: "The pupils listen to the teacher.",
    categoryId: "school",
  },
  {
    id: "computer",
    en: "computer",
    cs: "počítač",
    emoji: "💻",
    sentence: "We use a computer in class.",
    categoryId: "school",
  },

  // Sloveso To Be
  { id: "tb-i-am", en: "I am", cs: "já jsem", emoji: "🙋", sentence: "I am a happy pupil.", categoryId: "toBe" },
  {
    id: "tb-you-ty",
    en: "You are",
    cs: "ty jsi",
    emoji: "👤",
    sentence: "You are my friend.",
    categoryId: "toBe",
  },
  {
    id: "tb-you-vy",
    en: "You are",
    cs: "vy jste",
    emoji: "👥",
    sentence: "You are very kind, class.",
    categoryId: "toBe",
  },
  { id: "tb-he-is", en: "He is", cs: "on je", emoji: "👦", sentence: "He is my brother.", categoryId: "toBe" },
  {
    id: "tb-she-is",
    en: "She is",
    cs: "ona je",
    emoji: "👧",
    sentence: "She is my teacher.",
    categoryId: "toBe",
  },
  { id: "tb-it-is", en: "It is", cs: "ono je", emoji: "📦", sentence: "It is a sunny day.", categoryId: "toBe" },
  {
    id: "tb-we-are",
    en: "We are",
    cs: "my jsme",
    emoji: "👫",
    sentence: "We are in the same class.",
    categoryId: "toBe",
  },
  {
    id: "tb-they-are",
    en: "They are",
    cs: "oni jsou",
    emoji: "👨‍👩‍👧",
    sentence: "They are my classmates.",
    categoryId: "toBe",
  },
  {
    id: "tb-i-am-not",
    en: "I am not",
    cs: "já nejsem",
    emoji: "🚫",
    sentence: "I am not sad today.",
    categoryId: "toBe",
  },
  {
    id: "tb-are-you",
    en: "Are you?",
    cs: "Jsi ty?",
    emoji: "❓",
    sentence: "Are you ready for school?",
    categoryId: "toBe",
  },
  {
    id: "tb-is-he",
    en: "Is he?",
    cs: "Je on?",
    emoji: "❓",
    sentence: "Is he at home?",
    categoryId: "toBe",
  },
  {
    id: "tb-is-she",
    en: "Is she?",
    cs: "Je ona?",
    emoji: "❓",
    sentence: "Is she your sister?",
    categoryId: "toBe",
  },
  {
    id: "tb-im-happy",
    en: "I'm happy",
    cs: "Jsem šťastný",
    emoji: "😊",
    sentence: "I'm happy on my birthday.",
    categoryId: "toBe",
  },
  {
    id: "tb-she-is-tall",
    en: "She is tall",
    cs: "Ona je vysoká",
    emoji: "👩",
    sentence: "She is tall like a basketball player.",
    categoryId: "toBe",
  },
  {
    id: "tb-he-is-funny",
    en: "He is funny",
    cs: "On je vtipný",
    emoji: "😄",
    sentence: "He is funny and kind.",
    categoryId: "toBe",
  },
  {
    id: "tb-we-are-friends",
    en: "We are friends",
    cs: "Jsme kamarádi",
    emoji: "🤝",
    sentence: "We are friends forever.",
    categoryId: "toBe",
  },
  {
    id: "tb-it-is-cold",
    en: "It is cold",
    cs: "Je zima",
    emoji: "🥶",
    sentence: "It is cold in winter.",
    categoryId: "toBe",
  },
  {
    id: "tb-they-are-nice",
    en: "They are nice",
    cs: "Jsou hodní",
    emoji: "😇",
    sentence: "They are nice to everyone.",
    categoryId: "toBe",
  },
  {
    id: "tb-what-is-it",
    en: "What is it?",
    cs: "Co to je?",
    emoji: "❔",
    sentence: "What is it in the box?",
    categoryId: "toBe",
  },
  {
    id: "tb-how-old-are-you",
    en: "How old are you?",
    cs: "Kolik ti je let?",
    emoji: "🎂",
    sentence: "How old are you this year?",
    categoryId: "toBe",
  },

  // Sloveso To Have
  {
    id: "th-i-have",
    en: "I have",
    cs: "já mám",
    emoji: "🙋",
    sentence: "I have a new bag.",
    categoryId: "toHave",
  },
  {
    id: "th-you-tu",
    en: "You have",
    cs: "ty máš",
    emoji: "👤",
    sentence: "You have a red pencil.",
    categoryId: "toHave",
  },
  {
    id: "th-you-vu",
    en: "You have",
    cs: "vy máte",
    emoji: "👥",
    sentence: "You have good ideas, everyone.",
    categoryId: "toHave",
  },
  {
    id: "th-he-has",
    en: "He has",
    cs: "on má",
    emoji: "👦",
    sentence: "He has a small dog.",
    categoryId: "toHave",
  },
  {
    id: "th-she-has",
    en: "She has",
    cs: "ona má",
    emoji: "👧",
    sentence: "She has a blue bike.",
    categoryId: "toHave",
  },
  {
    id: "th-it-has",
    en: "It has",
    cs: "ono má",
    emoji: "📦",
    sentence: "It has four legs.",
    categoryId: "toHave",
  },
  {
    id: "th-we-have",
    en: "We have",
    cs: "my máme",
    emoji: "👫",
    sentence: "We have English on Monday.",
    categoryId: "toHave",
  },
  {
    id: "th-they-have",
    en: "They have",
    cs: "oni mají",
    emoji: "👨‍👩‍👧",
    sentence: "They have a big garden.",
    categoryId: "toHave",
  },
  {
    id: "th-i-dont-have",
    en: "I don't have",
    cs: "já nemám",
    emoji: "🚫",
    sentence: "I don't have a sister.",
    categoryId: "toHave",
  },
  {
    id: "th-do-you-have",
    en: "Do you have?",
    cs: "Máš ty?",
    emoji: "❓",
    sentence: "Do you have a pen?",
    categoryId: "toHave",
  },
  {
    id: "th-does-he-have",
    en: "Does he have?",
    cs: "Má on?",
    emoji: "❓",
    sentence: "Does he have a football?",
    categoryId: "toHave",
  },
  {
    id: "th-i-have-a-dog",
    en: "I have a dog",
    cs: "Mám psa",
    emoji: "🐕",
    sentence: "I have a dog at home.",
    categoryId: "toHave",
  },
  {
    id: "th-she-has-a-cat",
    en: "She has a cat",
    cs: "Ona má kočku",
    emoji: "🐱",
    sentence: "She has a cat named Luna.",
    categoryId: "toHave",
  },
  {
    id: "th-he-has-a-bike",
    en: "He has a bike",
    cs: "On má kolo",
    emoji: "🚲",
    sentence: "He has a bike with a bell.",
    categoryId: "toHave",
  },
  {
    id: "th-we-have-a-car",
    en: "We have a car",
    cs: "Máme auto",
    emoji: "🚗",
    sentence: "We have a car for trips.",
    categoryId: "toHave",
  },
  {
    id: "th-i-have-lunch",
    en: "I have lunch",
    cs: "Jím oběd",
    emoji: "🥪",
    sentence: "I have lunch at school.",
    categoryId: "toHave",
  },
  {
    id: "th-she-has-breakfast",
    en: "She has breakfast",
    cs: "Ona snídá",
    emoji: "🍳",
    sentence: "She has breakfast at seven.",
    categoryId: "toHave",
  },
  {
    id: "th-do-you-have-a-pen",
    en: "Do you have a pen?",
    cs: "Máš pero?",
    emoji: "🖊️",
    sentence: "Do you have a pen for me?",
    categoryId: "toHave",
  },
  {
    id: "th-i-have-blue-eyes",
    en: "I have blue eyes",
    cs: "Mám modré oči",
    emoji: "👀",
    sentence: "I have blue eyes like Mum.",
    categoryId: "toHave",
  },
  {
    id: "th-he-has-blond-hair",
    en: "He has blond hair",
    cs: "Má blond vlasy",
    emoji: "👱",
    sentence: "He has blond hair and a smile.",
    categoryId: "toHave",
  },
];

export const TOTAL_VOCABULARY_COUNT = VOCABULARY_WORDS.length;

export function getWordsByCategory(categoryId: CategoryId): Word[] {
  return VOCABULARY_WORDS.filter((w) => w.categoryId === categoryId);
}

export function getCategoryMeta(
  categoryId: CategoryId,
): CategoryMeta | undefined {
  return VOCABULARY_CATEGORIES.find((c) => c.id === categoryId);
}

export function getWordById(wordId: string): Word | undefined {
  return VOCABULARY_WORDS.find((w) => w.id === wordId);
}
